name: React CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Npm install Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install NPM dependencies
      run: npm i
    - name: Build Project
      run: npm run build

    - name: Run tests
      run: npm test --coverage
